### ISSUE TITLE
Could you enhance the efficiency of this package? it is too slow than the reghdfe in Stata.

### ISSUE THREAD

**Issue by kennyzjc1994** [jeffgortmaker/pyhdfe#1] opened 2022-05-05 02:08 UTC
Could you enhance the efficiency of this package? it is too slow than the `reghdfe` in Stata.

I really want to change my econometric software from Stata to pure python. but this is really difficult. 

I have compared regpyhdfe and reghdfe, the calculation captures too much time in python than stata

**Comment by jeffgortmaker** [comment] 2022-05-05 15:32
I wish I could work on this, but I really don't have the time for the foreseeable future. Personally, I've mainly used this package as a backend for fixed effect absorption for my PyBLP package, where absorption isn't the resource bottleneck (unlike running simple regressions, where as you note it definitely can be).

I can't speak to the regpyhdfe package since I didn't write it. I can say that compared to reghdfe, there are at least 3 reasons why PyHDFE might be slower:
1. We haven't implemented [Correia's (2016)](http://scorreia.com/research/hdfe.pdf) algorithm that leverages advances in spectral graph theory. My understanding is that this is the primary algorithm used by reghdfe, and it will be faster in many situations.
2. Although we've implemented a number of algorithms, which may be slower or faster on certain datasets than the algorithm primarily used by reghdfe, we haven't put a ton of effort into optimizing them a lot. More work could be done here, but it will require profiling code and maybe rewriting small parts of it in a lower-level language or using some package that JIT compiles Python code.
3. The default algorithm you're using may simply not be the fastest for the dataset you're working with.
4. The regpyhdfe package may introduce additional overhead that reghdfe has managed to minimize. Again, can't really speak to this -- PyHDFE just residualizes matrices.

Right now, my going recommendation for regressions with high dimensional fixed effects in Python is actually to use the wonderful [fixest](https://lrberge.github.io/fixest/) package in R via [rpy2](https://rpy2.github.io/). There is some overhead passing objects between R and Python, but if most of the computation time is in residualizing matrices, this shouldn't matter too much. And honestly, the main bottleneck in my experience with running regressions in Python isn't fixed effect absorption speed, but rather a lack of estimator implementations (different standard errors, post-estimation tests, etc.).

This said, we're of course more than happy to accept contributions, if you're interested in speeding up the package. I do wish there existed a fixest or reghdfe for Python, and my hope was that someone would build one on top of PyHDFE, but that's really quite a lot of work. Formal speed tests (e.g., comparing different algorithms on simulated or real datasets with other implementations) would also be wonderful, but I don't have the time to do these at the moment.

Hope this helps, and sorry I can't be of too much help here. I'm going to close this issue, but feel free to keep commenting and I'm happy to answer any more questions.

**Closed as completed by jeffgortmaker** 2022-05-05 15:32 UTC
Labels: question
